### ISSUE TITLE
Redesign dataset page to include new fields from Project Open Data

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#366]
The dataset page should be redesigned to include all the links and other core information provided in the Project Open Data data.json schema rather than only have that information displayed in the table under "About this Dataset"

For example, links specified by `landingPage`, `references`, `dataDictionary`, and `webService` could be displayed more prominently - more like how accessURLs are currently listed

Since there a lot of changes here, they've been broken into sub-tasks. 

The first section of sub-tasks (1-7) goes along with [the mockup in the comment below](https://github.com/GSA/data.gov/issues/366#issuecomment-51666027)
- [ ] 1. This header breadcrumb was redundant with the the breadcrumb below it and other links to the catalog home page and organizations. The help link was moved below as well.
- [x] 2. The title of the dataset was repeated twice in the same place here in the breadcrumb and in the main title heading just below it. Let's remove it in the breadcrumb and instead replace it with the Publisher field if that's available. 
- [ ] Only show the publisher field in the breadcrumb if the name of the publisher is different than the name of the organization. 
- [ ] 3. The date the data was last updated should be down prominently here, but this should link down to the section with all the other dates lower in the page. 
- [x] 4. This should link to faceted search results for this publisher
- [x] 5. This should link to the email address for the contact (mbox)
- [x] 6. The download and preview buttons should be separated for any filetype that support previews (mostly CSV)
- [x] 7. These fields should be shown as resources along side the downloadable links. This is especially important if no downloadable links are provided since these links are usually the second best thing. 
- [x] The list of references should be provided as a separate section
- [ ] All date fields should also be visible as a separate section. Also tracked in #594
- [x] Publisher and contact information should be displayed in the left sidebar
- [x] Topics should be displayed in the left sidebar
- [x] There should be a prominently displayed message indicating when dataset downloads are knowingly not made available so it doesn't look like an error. [See mockup](https://github.com/GSA/data.gov/issues/366#issuecomment-58273828). Also tracked in #348
- [x] Display access level more prominently when not public. Also tracked in #606 
- [x] Show "Report an issue with this Dataset" button provided by #131 and #422. _mockup needed_
- [ ] Incorporate QA errors into the display of resources as described in #471. _mockup needed_  
- [x] When terms of use vary for a non-federal source, this needs to be displayed prominently (drawn from harvest source metadata or custom fields associated with the organization). More details in #463 and #622 (mockup included)
- [x] Show topic categories (either in the sidebar with topics or with tags). More details in #658 
- [x]  Include optional fields for v1.1 schema update (#488)
- [ ]  Show relevant issues on Open Data Stack Exchange (#82)

**Comment by JeanneHolm** [comment]
Concern that there may be too many download options at the top, and that the agencies may want to prioritize certain services. See, for example, Consumer Complaint Database: http://catalog.data.gov/dataset/consumer-complaint-database. 

Suggestion is to modify POD description to recommend proper references to bring prioritized services to the top as downloads. Will also change from plain text to links in the metadata description.

**Comment by abrown920** [comment]
Here's a wireframe of the redesigned dataset page. 
![updated dataset page wireframe](https://cloud.githubusercontent.com/assets/7989692/3604589/d676592c-0d21-11e4-963d-6e076b8bfa06.jpg)

**Comment by kvuppala** [comment]
@philipashlock let us know if the above looks fine.

**Comment by JeanneHolm** [comment]
Fixed for show hyperlinks for all url fields in About this dataset section of the dataset

**Comment by philipashlock** [comment]
@JeanneHolm This hasn't been completed yet. Reopening and adding back to 2.9

**Comment by philipashlock** [comment]
Here's a mockup along with a version with numbered sections to go with these annotations:
1. This header breadcrumb was redundant with the the breadcrumb below it and other links to the catalog home page and organizations. The help link was moved below as well.
2. The title of the dataset was repeated twice in the same place here in the breadcrumb and in the main title heading just below it. Let's remove it in the breadcrumb and instead replace it with the Publisher field if that's available. 
3. The date the data was last updated should be down prominently here, but this should link down to the section with all the other dates lower in the page. 
4. This should link to faceted search results for this publisher
5. This should link to the email address for the contact (mbox)
6. The download and preview buttons should be separated for any filetype that support previews (mostly CSV)
7. These fields should be shown as resources along side the downloadable links. This is especially important if no downloadable links are provided since these links are usually the second best thing. 

The highest priorities are to address number 6 and 7. Displaying the Landing Page as a resource is probably the very highest priority in this redesign. 

There's an argument to be made that the Landing Page and Data Dictionary should be listed even more prominently than the downloads, but there's also an argument to be made that actual download links should be given as much priority as possible since that should be what people care about most. 

**Annotated mockup:**
![dataset-page-markup](https://cloud.githubusercontent.com/assets/183402/3863643/29108838-1f4c-11e4-801c-22729afd267b.png)

## 

## 

## 

## 

**Full mockup** (there's a [more updated mockup below](https://github.com/GSA/data.gov/issues/366#issuecomment-54519865))
![dataset-page](https://cloud.githubusercontent.com/assets/183402/3863637/12b67d2c-1f4c-11e4-9f7b-ae26974f2086.png)

**Comment by ErieMeyer** [comment]
Phil -- this is GORGEOUS. I love it.

**Comment by nsinai** [comment]
+1!  Looks great!

Couple questions:
1) What are the references?
2) Would it make sense to be explicit about the URL where the metadata is harvested?

**Comment by philipashlock** [comment]
@nsinai 

1) as defined by [Project Open Data](http://project-open-data.github.io/schema/) "references" (aka "Related Documents"):

> Related documents such as technical information about a dataset, developer documentation, etc.

We might consider having links for some of these headings and labels that point to documentation explaining what they are.

2) - I suppose it might be of interest for some to show the full URL for the harvest source here, but we do already provide a link to more information which includes the full URL.

**Comment by nsinai** [comment]
Thanks!

1)      “Related documents” seems to be more user-friendly and obvious than “references” -- that’s why I suggested we use it.  If we want to keep Project Open Data definitions, than perhaps we could be descriptive in the title: “References (e.g. related documents, technical info, etc.).”  But up to you!

2)      Would a user know what “GSA JSON” refers to?  Shouldn’t we call it “GSA’s public data listing (in JSON)” or something like that?

If these are more appropriate for user testing, that’s fine too, just trying to make sure we make it easy for the novice reader/user to understand…!

**Comment by philipashlock** [comment]
TODO for me: 
- update mockup with publisher/contact in the sidebar under organization. 
- provide bootstrap classes for icons in 7

**Comment by philipashlock** [comment]
Here's an update with the publisher and contact info moved over to the sidebar. 

Fontawesome icons used:
- book: http://fontawesome.io/icon/book/
- calendar: http://fontawesome.io/icon/calendar/
- university: http://fontawesome.io/icon/university/
- envelope: http://fontawesome.io/icon/envelope/
- cloud download: http://fontawesome.io/icon/cloud-download/
- globe: http://fontawesome.io/icon/globe/
- info: http://fontawesome.io/icon/info-circle/

![dataset-page-revision2](https://cloud.githubusercontent.com/assets/183402/4153967/c80b2f3a-345d-11e4-932e-7f1c5965c558.png)

**Comment by philipashlock** [comment]
TODO: mockup a better UI and copy for when download links haven't been provided. We didn't really clarify this with #307. Also duplicate of #348 

Examples: http://catalog.data.gov/dataset?q=num_resources:0

**Comment by rebeccawilliams** [comment]
+1 These mockups look great! 

Can we also use the dataset redesign as an opportunity to provide a space for immediate (and directed!) feedback on dataset improvements; e.g. broken links, of which we get _many_ reported as Issues, see: #455, #453, #449, #442, #438, #416, #410, #404, #403, and #294.

My suggestion would be add a "Report an issue with this Dataset" button at the bottom of the page that has a mailto: link to the Maintainer Email.

**Comment by philipashlock** [comment]
Also need to add Topic and Category - perhaps in sidebar. Also mockup "report an issue" button

**Comment by kvuppala** [comment]
@philipashlock 
Publisher and Contact sections are updated as per the mockup.

Topics is already present as below:
![topics_section-_data gov_-_2014-09-29_13 49 37](https://cloud.githubusercontent.com/assets/1738764/4446257/bf2dc646-4800-11e4-994b-0583ddefc7a3.png)

Should we create a separate ticket for future release for Topic Category and Report an Issue button sections mockup, each topic potentially could have multiple categories associated, not sure if we want to show them on the left section or come up with a different section after or before "About this dataset" section.

**Comment by philipashlock** [comment]
@kvuppala, several aspects of this were completed, but certainly not the whole thing, so let's keep this one open until complete. Since there are several different sub tasks on this issue, I've gone ahead and made them all part of a to-do list with check marks to make it easier to track what's done. Some of these sub tasks also refer to other issues and I've linked to those too. Normally, it would make sense to break everything into a separate issue, but since most of the sub-tasks are about how to display elements together on this one page, and since it's helpful to have one thread to engage the public in the design process, I think it's better to show everything here.

**Comment by philipashlock** [comment]
Here's a mockup for a dataset where no `accessURL` links were provided. This would also address #348

![dataset-page-no-downloads](https://cloud.githubusercontent.com/assets/183402/4551464/aa27dd0a-4e71-11e4-8586-744f3a35ff8a.png)

**Comment by kvuppala** [comment]
Below item from the master list is completed in 2.11, remaining items need to be worked on.
<<
There should be a prominently displayed message indicating when dataset downloads are knowingly not made available so it doesn't look like an error. See mockup. Also tracked in #348

**Comment by hkdctol** [comment]
@kvuppala can you review and close if appropriate

**Comment by hkdctol** [comment]
@kvuppala are there any elements still open on this issue?

**Comment by kvuppala** [comment]
@hkdctol @philipashlock I think we close this, most of the parts are complete and few others have their own separate github issue to track.
