### ISSUE TITLE
HHS Broken Links 

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#551]
- [x] [FDA Drug Label](https://catalog.data.gov/dataset/fda-drug-label-data) see #467 
- [ ] [State By State Behavioral Health Resources (SAMHSA)](http://catalog.data.gov/dataset/state-by-state-behavioral-health-resources) see #517
- [ ] [Social Media Metrics (SAMHSA)](http://catalog.data.gov/dataset/social-media-monitoring-metrics) see #389

@DamonDavis, I've consolidated the reported broken link issues to this thread for follow up.

**Comment by rebeccawilliams** [comment]
@DamonDavis, looks like the FDA Drug Label link is updated [here](http://catalog.data.gov/dataset/fda-online-label-repository). 

Are the appropriate http://www.samhsa.gov/ URLs from above going to be added to the data.json?

Or this [dataset](http://catalog.data.gov/dataset/samhsa-federated-datasets) could be turned into a parent Collection.

**Comment by DamonDavis** [comment]
Sorry Rebecca, i'm not following your questions here.

FDA's drug labeling information through openFDA is wholly separate from any activity coming out of SAMHSA, the Substance Abuse and Mental Health Services Adminstration?

Can you clarify what relationship you're seeing here please?

Damonhttp://about.me/damondavis | 301.646.8292-m| 202.774.2307-o | HHS IDEA Lab | HealthData.gov | @damonldavishttps://twitter.com/damonldavis

**Comment by rebeccawilliams** [comment]
There were a few broken links reported. The FDA Drug Label link is fixed, success! 

The two remaining links are from SAMHSA, specifically: "State By State Behavioral Health Resources" and "Social Media Metrics". Can we get these datasets listed in the HHS data.json with the new URLs. See background on the links [here](https://github.com/GSA/data.gov/issues/551#issuecomment-74954507). 

We want users to be able to find that information on Data.gov like they once could.

**Comment by DamonDavis** [comment]
Glad fda is fixed.

SAMHSA took down its links for a variety of reasons and the social media one was among the first to go. I removed it from the healthdata.govhttp://healthdata.gov Json file quite a while ago. How does data.govhttp://data.gov get updated for dataset removals  in order to maintain the integrity of the catalog? It's great at sucking in additions, but deletions seem to be a challenge.

Damonhttp://about.me/damondavis | 301.646.8292-m | 202.619.3807-o | HHS IDEA Lab | HealthData.govhttp://HealthData.gov | @damonldavis

On Feb 18, 2015, at 5:11 PM, Rebecca Williams <notifications@github.com<mailto:notifications@github.com>> wrote:

There were a few broken links reported. The FDA Drug Label link is fixed, success!

The two remaining links are from SAMHSA, specifically: "State By State Behavioral Health Resources" and "Social Media Metrics". Can we get these datasets listed in the HHS data.json with the new URLs. See background on the links herehttps://github.com/GSA/data.gov/issues/551#issuecomment-74954507.

We want users to be able to find that information on Data.govhttp://Data.gov like they once could.

**Comment by rebeccawilliams** [comment]
The deletions no longer show up on Data.gov automatically as well. These URLs were reported broken before the metadata was deleted. However since SAMHSA data exists it should be listed in the data.json per the Open Data Policy.

**Comment by DamonDavis** [comment]
Hey Rebecca,

You may know the HHS IDEA Lab team will be over at 18f all next week. Wanna chat about HHS data strategy since we'll be on scene?

Damonhttp://about.me/damondavis | 301.646.8292-m | 202.619.3807-o | HHS IDEA Lab | HealthData.govhttp://HealthData.gov | @damonldavis

On Feb 18, 2015, at 7:39 PM, Rebecca Williams <notifications@github.com<mailto:notifications@github.com>> wrote:

The deletions no longer show up on Data.govhttp://Data.gov automatically as well. These URLs were reported broken before the metadata was deleted. However since SAMHSA data exists it should be listed in the data.json per the Open Data Policy.

**Comment by rebeccawilliams** [comment]
Sure, I will send an email!

**Comment by rebeccawilliams** [comment]
Available URLs are up to date.
