### ISSUE TITLE
Update Digital Analytics Program (DAP) tracking code

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#599]
In response to https://www.digitalgov.gov/services/dap/digital-analytics-program-universal-analytics-migration/
- [x] data.gov (https://github.com/GSA/data.gov/pull/596)
- [x] catalog.data.gov (https://github.com/GSA/ckanext-geodatagov/pull/93)
- [x] labs.data.gov/dashboard (https://github.com/GSA/project-open-data-dashboard/commit/da27a3fce7dc549ea9858875d758121bff0c4518)
- [x] inventory.data.gov
- [ ] others?

**Comment by vasili4** [comment]
inventory.data.gov - could not find any existing DAP code.
we can add it to GSA/ckanext-googleanalyticsbasic/pull/1

I just switched Google Analytics tracker of inventory to Universal one, so everything must go smooth.

**Comment by kvuppala** [comment]
all the main sites universal analytics is complete
